export const modelOptions = {
    Studio: ["en-US-Studio-O", "en-US-Studio-Q"],
    Journey: ["en-US-Journey-D", "en-US-Journey-F", "en-US-Journey-O"],
    Casual: ["en-US-Casual-K"],
    Polyglot: ["en-US-Polyglot-1"],
    Neural: [
      "en-US-Neural2-A",
      "en-US-Neural2-C",
      "en-US-Neural2-D",
      "en-US-Neural2-E",
      "en-US-Neural2-F",
      "en-US-Neural2-G",
      "en-US-Neural2-H",
      "en-US-Neural2-I",
      "en-US-Neural2-J",
    ],
    News: ["en-US-News-K", "en-US-News-L", "en-US-News-N"],
    Standard: [
      "en-US-Standard-A",
      "en-US-Standard-B",
      "en-US-Standard-C",
      "en-US-Standard-D",
      "en-US-Standard-E",
      "en-US-Standard-F",
      "en-US-Standard-G",
      "en-US-Standard-H",
      "en-US-Standard-I",
      "en-US-Standard-J",
    ],
    Wavenet: [
      "en-US-Wavenet-A",
      "en-US-Wavenet-B",
      "en-US-Wavenet-C",
      "en-US-Wavenet-D",
      "en-US-Wavenet-E",
      "en-US-Wavenet-F",
      "en-US-Wavenet-G",
      "en-US-Wavenet-H",
      "en-US-Wavenet-I",
      "en-US-Wavenet-J",
    ],
  };
  